sonar.projectKey=NudoStudio
sonar.projectName=NudoStudio
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000

# Analizar todo el código dentro de la carpeta actual
sonar.sources=.

# Carpetas que SonarQube no debe analizar
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.sourceEncoding=UTF-8